version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-winess
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: winess
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend-winess
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: winess
      JWT_SECRET: supersecret
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend-winess
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql-data:
